[build]
  publish = "."
  functions = "netlify/functions"

# Optional: single-page app fallback; keep if your index.html handles routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
