[build]
command = "npm i"
publish = "."
functions = "netlify/functions"

[functions]
external_node_modules = ["pg", "bcryptjs", "uuid"]
node_bundler = "esbuild"
included_files = ["netlify/functions/**"]
